\newcommand{\argxi}{(\xi_1,\xi_2,\xi_3)}
\newcommand{\argx}{(x_1,x_2,x_3)}

\newcommand{\argxbarn}{(\bar{x}^1,\bar{x}^2,\ldots, \bar{x}^n)}
\newcommand{\argxn}{(x^1, x^2,\ldots, x^n)}

\newcommand{\argtxi}{(t, \xi_1,\xi_2,\xi_3)}
\newcommand{\argtoxi}{(t_0, \xi^1,\xi^2,\xi^3)}
\newcommand{\argtx}{(t, x_1,x_2,x_3)}
\newcommand{\argtox}{(t_0, x^1,x^2,x^3)}

\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\pdk}[2]{\frac{\partial^2 #1}{\partial {#2}^2}}

%\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}
%\newcommand{\pdk}[2]{\frac{\partial^2 #1}{\partial {#2}^2}}